/** @type {import('tailwindcss').Config} */
// Tokens copied 1:1 from ../docs/admin/DESIGN.md and ../docs/admin/code.html
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#47464c",
        "surface-container": "#f1eded",
        "primary-fixed": "#e4e1e8",
        background: "#fdf8f8",
        "tertiary-container": "#211c15",
        "secondary-fixed-dim": "#c0c7d6",
        "primary-container": "#1c1c21",
        "on-primary-container": "#85848a",
        "on-surface": "#1c1b1c",
        "error-container": "#ffdad6",
        "on-background": "#1c1b1c",
        "on-secondary-fixed-variant": "#404754",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#8c837a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#201b14",
        "on-error-container": "#93000a",
        "on-surface-variant": "#47464b",
        "outline-variant": "#c8c5cb",
        "surface-variant": "#e5e2e2",
        "on-tertiary-fixed-variant": "#4c463d",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f7f3f3",
        "inverse-surface": "#313030",
        "surface-container-lowest": "#ffffff",
        tertiary: "#040200",
        outline: "#78767b",
        "on-primary-fixed": "#1b1b20",
        "surface-tint": "#5f5e64",
        "inverse-primary": "#c8c5cc",
        "surface-container-high": "#ebe7e7",
        "surface-bright": "#fdf8f8",
        "tertiary-fixed": "#ece1d5",
        "on-secondary-container": "#5e6572",
        "surface-container-highest": "#e5e2e2",
        "tertiary-fixed-dim": "#cfc5ba",
        "on-secondary-fixed": "#151c27",
        "surface-dim": "#ddd9d9",
        "inverse-on-surface": "#f4f0f0",
        "secondary-container": "#dce2f3",
        primary: "#010204",
        "primary-fixed-dim": "#c8c5cc",
        secondary: "#585f6c",
        error: "#ba1a1a",
        surface: "#fdf8f8",
        "on-error": "#ffffff",
        "secondary-fixed": "#dce2f3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
        gutter: "24px",
        "stack-lg": "24px",
        "sidebar-width": "240px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "headline-lg-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
